language: python
python:
    - "3.7.0"
install:
    - "pip install -r requirements.txt"
    - "pip install -e .[dev]"
script:
    - pytest --cov=dplaapi --cov-report=xml
    - flake8 dplaapi tests
    - python-codacy-coverage -r coverage.xml
